postgres:
  image: quay.io/azavea/postgis:2.2-postgres9.5-slim
  environment:
    - POSTGRES_DB=district_builder
    - POSTGRES_USER=district_builder
    - POSTGRES_PASSWORD=district_builder

redis:
  image: redis:3-alpine

django:
  build: .
  links:
    - postgres
    - redis
  ports:
    - 8080:8080
  # command:
  #   - /usr/bin/python /usr/src/app/django/publicmapping/manage.py
  #   - run_gunicorn
