postgres:
  image: mdillon/postgis:9.6-alpine
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres

redis:
  image: redis:3-alpine

django:
  build: .
  links:
    - postgres
    - redis
  ports:
    - 8080:8080
  command:
    - /usr/src/app/start.sh
